export const RESET_FILTER = 'RESET_FILTER';
export const CHANGE_MIN_PRICE = 'CHANGE_MIN_PRICE';
export const CHANGE_MAX_PRICE ='CHANGE_MAX_PRICE';
export const CHANGE_DISCOUNT = 'CHANGE_DISCOUNT';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
